<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Ekamban-Laptop" failures="1" tests="1" name="ValidationAssertFail" time="24.894" errors="0" timestamp="2020-09-24T17:06:44 NZST">
  <testcase classname="TP.E2ESelenium.ValidateTest" name="validateTest" time="5.032">
    <failure type="java.lang.AssertionError" message="expected [There is 1 erro] but found [There is 1 error]">
      <![CDATA[java.lang.AssertionError: expected [There is 1 erro] but found [There is 1 error]
at TP.E2ESelenium.ValidateTest.validateTest(ValidateTest.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- validateTest -->
</testsuite> <!-- ValidationAssertFail -->
